name: ecommers_new
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Iconos de Cupertino
  cupertino_icons: ^1.0.8
  
  # Dependencias adicionales
  animated_text_kit: ^4.2.2
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.16
  font_awesome_flutter: ^10.8.0
  getwidget: ^4.0.0
  google_sign_in: ^6.2.2
  http: ^1.2.2
  modal_progress_hud_nsn: ^0.5.1
  persistent_bottom_nav_bar: ^6.2.1
  persistent_bottom_nav_bar_v2: ^5.3.1
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true